# SPDX-License-Identifier: GPL-2.0
snd-soc-qdsp6v2-objs := msm-audio-effects-q6-v2.o msm-compress-q6-v2.o msm-dai-fe.o msm-dai-q6-hdmi-v2.o msm-dai-q6-v2.o msm-dai-stub-v2.o msm-lsm-client.o msm-pcm-afe-v2.o msm-pcm-dtmf-v2.o msm-pcm-hostless.o msm-pcm-host-voice-v2.o msm-pcm-loopback-v2.o msm-pcm-q6-noirq.o msm-pcm-q6-v2.o msm-pcm-routing-v2.o msm-pcm-voice-v2.o msm-pcm-voip-v2.o msm-transcode-loopback-q6-v2.o platform_init.o

obj-$(CONFIG_SND_SOC_QDSP6V2) += snd-soc-qdsp6v2.o
