# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_QTI_TZ_LOG) += tz_log.o
obj-$(CONFIG_QCOM_SCM)		+= qcom-scm.o
obj-$(CONFIG_QCOM_SCM_HAB)	+= qcom-scm-hab.o
obj-$(CONFIG_QTEE_SHM_BRIDGE) += qtee-shmbridge.o
